version: "3.9"

services:
  mongo_db:
    container_name: mongo_db
    image: mongo
    ports:
      - 27018:27017
    command: mongod
    env_file: .env
    volumes:
      - ./db/data:/data/db
    logging:
      driver: none
    networks:
      - pizza

mongo-express:
  image: mongo-express
  ports:
    - 8081:8081
  env_file: ./mongo_express/.env
  depends_on:
    - mongo_db
  networks:
    - pizza

networks:
  pizza:
    driver: bridge
